Dependencies:

In [39]:
import netCDF4	as nc
import numpy	as np
import pandas	as pd

import matplotlib.pyplot as plt
import xarray as xr
# import cartopy.crs as ccrs - currently dealing with broken dependencies ://
# https://geos.readthedocs.io/en/latest/users.html
# https://libgeos.org/usage/download/
# https://scitools.org.uk/cartopy/docs/latest/installing.html


Open forecast.nc dataset as a data array

In [29]:
fc = xr.open_dataarray('./forecast.nc')
fc


<xarray.DataArray 't2m' (time: 72, lat: 25, lon: 37)>
array([[[297.877  , 297.63263, ..., 299.25424, 299.30008],
        [297.74246, 297.74384, ..., 299.2265 , 299.3053 ],
        ...,
        [299.04578, 299.2516 , ..., 294.84918, 294.56836],
        [299.08432, 298.5864 , ..., 295.1606 , 295.1203 ]],

       [[297.46564, 297.10782, ..., 299.25485, 299.29617],
        [297.4523 , 297.36044, ..., 299.27005, 299.3341 ],
        ...,
        [298.6316 , 298.81693, ..., 294.4425 , 294.14966],
        [298.59766, 298.15414, ..., 294.75757, 294.67786]],

       ...,

       [[295.2503 , 294.71097, ..., 297.40695, 297.42773],
        [295.18915, 294.97858, ..., 297.5523 , 297.58896],
        ...,
        [297.19724, 297.2767 , ..., 291.21002, 290.67703],
        [297.59836, 296.94394, ..., 291.68857, 291.28857]],

       [[294.56735, 293.98807, ..., 297.3598 , 297.44885],
        [294.444  , 294.20996, ..., 297.52225, 297.59085],
        ...,
        [296.74274, 296.7859 , ..., 290.6997 , 290.27243],
        [296.8694 , 296.3436 , ..., 291.17657, 290.83813]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 -25.29 -25.07 -24.85 -24.63 ... -20.37 -20.14 -19.92
  * lon      (lon) float32 -52.99 -52.75 -52.51 -52.26 ... -44.74 -44.49 -44.25
  * time     (time) datetime64[ns] 2018-04-14 ... 2018-04-16T23:00:00

Open observation.nc dataset also as a data array

In [30]:

ob = xr.open_dataarray('./observation.nc')
ob

<xarray.DataArray 'temperatura' (time: 72, lat: 25, lon: 37)>
array([[[24.555346, 22.20913 , ..., 24.205818,       nan],
        [23.840425, 22.546028, ..., 24.124369,       nan],
        ...,
        [23.229092, 23.090694, ..., 18.455933, 19.171835],
        [22.799225, 23.16104 , ..., 18.255274, 19.366264]],

       [[23.0389  , 21.056534, ..., 24.088018,       nan],
        [22.427336, 21.402102, ..., 24.104513,       nan],
        ...,
        [22.154556, 22.138018, ..., 17.976265, 19.02524 ],
        [21.689274, 22.266026, ..., 17.89095 , 19.179226]],

       ...,

       [[20.864983, 20.555113, ..., 23.012321,       nan],
        [19.79059 , 20.03081 , ..., 23.089334,       nan],
        ...,
        [23.969128, 23.410042, ..., 18.679354, 18.17804 ],
        [23.27986 , 22.92126 , ..., 19.021667, 19.106825]],

       [[20.596725, 19.856867, ..., 22.478777,       nan],
        [19.287607, 19.183558, ..., 22.692806,       nan],
        ...,
        [22.975115, 22.516788, ..., 18.188711, 17.953955],
        [22.350718, 22.17121 , ..., 18.466291, 18.797155]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2018-04-14 ... 2018-04-16T23:00:00
  * lon      (lon) float32 -52.99 -52.75 -52.51 -52.26 ... -44.74 -44.49 -44.25
  * lat      (lat) float32 -25.29 -25.07 -24.85 -24.63 ... -20.37 -20.14 -19.92

Exploring time series for the coordinates in the first record

In [51]:
first_point = fc.isel(lat=2, lon=2)
first_point

<xarray.DataArray 't2m' (time: 72)>
array([297.57602, 297.27457, 296.9516 , 296.60788, 296.1428 , 295.6158 ,
       295.17197, 294.86804, 294.61407, 294.41434, 294.23157, 294.83044,
       295.97952, 297.11487, 298.1887 , 299.07275, 299.6872 , 300.05963,
       300.17853, 300.0376 , 299.53287, 298.27792, 297.20932, 296.6831 ,
       296.21573, 295.4866 , 294.71768, 294.10352, 293.6178 , 293.2186 ,
       292.88837, 292.6198 , 292.3967 , 292.20126, 292.02548, 292.6623 ,
       293.69266, 294.21213, 294.91818, 295.84586, 296.90067, 297.6302 ,
       297.9321 , 297.817  , 297.35217, 296.29303, 295.23456, 294.74765,
       294.37158, 293.86206, 293.1552 , 292.4267 , 291.80997, 291.33942,
       290.97546, 290.68616, 290.43695, 290.2111 , 290.00684, 290.8122 ,
       292.29437, 293.86655, 295.2948 , 296.36343, 297.19733, 297.73444,
       297.94998, 297.79254, 297.2165 , 295.9696 , 294.9332 , 294.2126 ],
      dtype=float32)
Coordinates:
    lat      float32 -24.85
    lon      float32 -52.51
  * time     (time) datetime64[ns] 2018-04-14 ... 2018-04-16T23:00:00

Now for São Paulo coordinates:

In [64]:
lat_sp = -23.5489
lon_sp = -46.6388

# Last step coded must be fixed
sp = fc.sel(lat=lat_sp, lon=lon_sp)
sp

AttributeError: NetCDF: Attribute not found

### Another possible exploratory data analysis:

In [56]:
forecast = nc.Dataset('./observation.nc')
forecast

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    CDI: Climate Data Interface version 1.9.1 (http://mpimet.mpg.de/cdi)
    Conventions: CF-1.6
    history: Thu Apr 19 18:43:01 2018: cdo remapbil,gridfile observation.nc _observation.nc
    CDO: Climate Data Operators version 1.9.1 (http://mpimet.mpg.de/cdo)
    dimensions(sizes): time(72), lon(37), lat(25)
    variables(dimensions): float32 time(time), float32 lon(lon), float32 lat(lat), float32 temperatura(time, lat, lon)
    groups: 

In [54]:
observation = nc.Dataset('./observation.nc')
observation

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    CDI: Climate Data Interface version 1.9.1 (http://mpimet.mpg.de/cdi)
    Conventions: CF-1.6
    history: Thu Apr 19 18:43:01 2018: cdo remapbil,gridfile observation.nc _observation.nc
    CDO: Climate Data Operators version 1.9.1 (http://mpimet.mpg.de/cdo)
    dimensions(sizes): time(72), lon(37), lat(25)
    variables(dimensions): float32 time(time), float32 lon(lon), float32 lat(lat), float32 temperatura(time, lat, lon)
    groups: 

In [57]:
lat_fc = forecast.variables['lat'][:]
lon_fc = forecast.variables['lon'][:]
lat_ob = observation.variables['lat'][:]
lon_ob = observation.variables['lon'][:]

In [59]:
for f in observation.variables['time']:
	print(f)
# print(observation.variables['time'])

24.0
25.0
26.0
27.0
28.0
29.0
30.0
31.0
32.0
33.0
34.0
35.0
36.0
37.0
38.0
39.0
40.0
41.0
42.0
43.0
44.0
45.0
46.0
47.0
48.0
49.0
50.0
51.0
52.0
53.0
54.0
55.0
56.0
57.0
58.0
59.0
60.0
61.0
62.0
63.0
64.0
65.0
66.0
67.0
68.0
69.0
70.0
71.0
72.0
73.0
74.0
75.0
76.0
77.0
78.0
79.0
80.0
81.0
82.0
83.0
84.0
85.0
86.0
87.0
88.0
89.0
90.0
91.0
92.0
93.0
94.0
95.0


In [63]:
dt_fc = forecast.variables['time']
print(dt_fc)

dt_ob = observation.variables['time']
print(dt_ob)

<class 'netCDF4._netCDF4.Variable'>
float32 time(time)
    standard_name: time
    units: hours since 2018-04-13 00:00
    calendar: standard
    axis: T
unlimited dimensions: time
current shape = (72,)
filling off
<class 'netCDF4._netCDF4.Variable'>
float32 time(time)
    standard_name: time
    units: hours since 2018-04-13 00:00
    calendar: standard
    axis: T
unlimited dimensions: time
current shape = (72,)
filling off
